providers = ["python"]

[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["pip install -r stalkea_clone/requirements.txt"]

[start]
cmd = "cd stalkea_clone && gunicorn server:app --bind 0.0.0.0:$PORT"
